### ISSUE TITLE
Formulas are not quite visible with GitHub's Dark Mode

### ISSUE THREAD

**Issue by chomelc** [dataiku/millenium-falcon-challenge#2]
![image](https://user-images.githubusercontent.com/57406944/171849526-b14e1c59-09a1-44cc-9627-e77db41782c9.png)

Perhaps you could directly inject the formulas in the README.md using LaTeX, instead of displaying images. I could open a PR if you want me to do it.

Thanks in advance!

**Comment by apichery** [comment]
Fixed
